### PR TITLE
fix: email absent in login callback bug

### LINKED ISSUE #980: when trying to signup with github or any third party auth if email is already used it show "null" email or ' ' is already used and shows some needless account numbers
Tested on: Windows Chorme

Screenshots:
**Github** 
image
**Twitter** 
image
**Facebook** 
image

steps to reproduce:
log in with email.
Log out of the account.
Try loging with any auth which you did not link with account

Yes i would like to work

### PR DESCRIPTION
**Pull request by prabalsingh24**
fixes #980, #634 

The callback from social websites (Github, Facebook, Twitter) may or may not contain email id (privacy might be public in case of github, you can make social media account only with mobile number too)

Here, see github shares only public details.
Screenshot_2020-05-20 Build software better, together

[profileJSON.email](https://github.com/coding-blocks/oneauth/blob/9c85ecb530ece704164972aa9826b1bdda13c7b7/src/passport/strategies/user/strategy-github.js#L83) can be null and will then fetch other `Users` with `null` emailId. (those `users` which were created from social media account with no email will have emailId as `null`)  and show that they have same email (`null === null` or `'' === ''` :P)

### CODE REVIEW

**Comment by prabalsingh24** [comment]
This was the response from github ( No emailId )

```
{ 
  login: 'prabalsingh24',
  id: 45737735,
  node_id: 'MDQ6VXNlcjQ1NzM3NzM1',
  avatar_url: 'https://avatars0.githubusercontent.com/u/45737735?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/prabalsingh24',
  html_url: 'https://github.com/prabalsingh24',
  followers_url: 'https://api.github.com/users/prabalsingh24/followers',
  following_url:
   'https://api.github.com/users/prabalsingh24/following{/other_user}',
  gists_url: 'https://api.github.com/users/prabalsingh24/gists{/gist_id}',
  starred_url:
   'https://api.github.com/users/prabalsingh24/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/prabalsingh24/subscriptions',
  organizations_url: 'https://api.github.com/users/prabalsingh24/orgs',
  repos_url: 'https://api.github.com/users/prabalsingh24/repos',
  events_url:
   'https://api.github.com/users/prabalsingh24/events{/privacy}',
  received_events_url: 'https://api.github.com/users/prabalsingh24/received_events',
  type: 'User',
  site_admin: false,
  name: null,
  company: null,
  blog: '',
  location: null,
  hireable: null,
  bio: 'IIT Guwahati',
  public_repos: 21,
  public_gists: 0,
  followers: 3,
  following: 2,
  created_at: '2018-12-09T16:37:09Z',
  updated_at: '2020-05-20T11:52:00Z' 
}
```

**Comment by prabalsingh24** [comment]
@championswimmer Have a look at this whenever you're free :)

File: src/passport/strategies/user/strategy-google.js [hunk 1]
```diff
@@ -55,6 +55,10 @@ module.exports = new GoogleStrategy({
                     b. Someone is trying to login via Google
                  */
 
+                if (!profileJson.email) {
```
Comment (prabalsingh24) [inline src/passport/strategies/user/strategy-google.js:58]: I don't think this will ever happen. But better to be on the safe side :)

File: src/passport/strategies/user/strategy-google.js [hunk 2]
```diff
@@ -55,6 +55,10 @@ module.exports = new GoogleStrategy({
...
+                    return cb(null, false, {message: "Can't fetch your Google account. Try some other login method"})
+                }
```
Comment (prabalsingh24) [inline src/passport/strategies/user/strategy-google.js:60]: I don't think this will ever happen with google account. But better to be on the safe side :)

**Comment by prabalsingh24** [comment]
How do you want this issue to be solved. The other option is to allow user to login but `userEmail` column will be null.

**Comment by championswimmer** [comment]
we have to add a interstial page where we make them enter an email id. making the email verified is not necessary, just for account creation purpose.

thing is there are multiple services (like ide) where we want to allow users to use without email id, if they have come via sso.
